name: API Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: api/yarn.lock

      - name: Install dependencies
        working-directory: ./api
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ./api
        run: yarn test
