name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: false # Disable automatic caching

      # Install and test in the API directory
      - name: Run API tests
        working-directory: api
        run: |
          yarn install
          yarn test

      # Install and test in the Frontend directory
      - name: Run Frontend tests
        working-directory: frontend
        run: |
          yarn install
          yarn test
